#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#d90762E6'
TEXT='#d90762E6'
WRONG='#6b0202bb'
VERIFYING='#28eb69E6'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 20                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"        \
--date-str="%A %d-%m-%Y"       \
